const HEADCODE_DATA = [
    {
        id: 1,
        arrival: "5D01",
        powerType: "801 E",
        time: "0343",
        info: "10 Car",
        departure: "05.55",
        by: "D1/IC",
        headcode: "1D01",
        to: "LDS",
        next: "1A18"
    },
    {
        id: 2,
        arrival: "3S04",
        powerType: "Mk4",
        time: "0202",
        departure: "06.15",
        by: "D1",
        headcode: "1S04",
        to: "EDB",
        next: "1E21"
    },
    {
        id: 3,
        arrival: "5D02",
        powerType: "Mk4",
        time: "0500",
        departure: "06.33",
        by: "D1",
        headcode: "1D02",
        to: "LDS",
        next: "1A19"
    },
    {
        id: 4,
        arrival: "5S05",
        powerType: "801 E",
        time: "0631",
        info: "9 Car",
        departure: "07.00",
        by: "D1",
        headcode: "1S05",
        to: "EDB",
        next: "1E14"
    },
    {
        id: 5,
        arrival: "5D03",
        powerType: "Mk4",
        time: "0624",
        departure: "07.03",
        by: "D2",
        headcode: "1D03",
        to: "LDS",
        next: "1A20"
    },
    {
        id: 6,
        arrival: "5N80",
        powerType: "Mk4",
        time: "0609",
        departure: "07.06",
        by: "D3",
        headcode: "1N80",
        to: "YRK",
        next: "1Y82"
    },
    {
        id: 7,
        arrival: "3S06",
        powerType: "800 Bi",
        time: "0048",
        departure: "07.30",
        by: "D1",
        headcode: "1S06",
        to: "EDB",
        next: "1E16"
    },
    {
        id: 8,
        arrival: "5D04",
        powerType: "Mk4",
        time: "0647",
        info: "10 Car",
        departure: "07.33",
        by: "D2/3",
        headcode: "1D04",
        to: "HGT",
        next: "1A29"
    },
    {
        id: 9,
        arrival: "1Y00",
        powerType: "Mk4",
        time: "0659",
        departure: "08.00",
        by: "D3",
        headcode: "1S07",
        to: "EDB",
        next: "1E17"
    },
    {
        id: 10,
        arrival: "1A01",
        powerType: "Mk4",
        time: "0728",
        departure: "08.03",
        by: "D2",
        headcode: "1D05",
        to: "LDS",
        next: "1A25"
    },
    {
        id: 11,
        arrival: "5B90",
        powerType: "800 Bi",
        time: "0741",
        info: "5 Car",
        departure: "08.06",
        by: "D1",
        headcode: "1B80",
        to: "LCN",
        next: "1B83"
    },
    {
        id: 12,
        arrival: "5N80",
        powerType: "Mk4",
        time: "0747",
        departure: "08.30",
        by: "D2",
        headcode: "1S08",
        to: "NCL",
        next: "1E18"
    },
    {
        id: 13,
        arrival: "1A02",
        powerType: "801 E",
        time: "0747",
        info: "9 Car",
        departure: "08.33",
        by: "D3",
        headcode: "1D06",
        to: "LDS",
        next: "1A26"
    },
    {
        id: 14,
        arrival: "1Y03",
        powerType: "Mk4",
        time: "0808",
        departure: "09.00",
        by: "D2",
        headcode: "1S09",
        to: "EDB",
        next: "1E19"
    },
    {
        id: 15,
        arrival: "5D07",
        powerType: "801 E",
        time: "0825",
        info: "10 Car",
        departure: "09.03",
        by: "D4/1",
        headcode: "1D07",
        to: "LDS",
        next: "1A28"
    },
    {
        id: 16,
        arrival: "1A04",
        powerType: "801 E",
        time: "0829",
        info: "10 Car",
        departure: "09.06",
        by: "D3/5",
        headcode: "1N81",
        to: "YRK",
        next: "1Y84"
    },
    {
        id: 17,
        arrival: "1Y05",
        powerType: "Mk4",
        time: "0838",
        departure: "09.30",
        by: "D4/1",
        headcode: "1S10",
        to: "EDB",
        next: "1E20"
    },
    {
        id: 18,
        arrival: "1A07",
        powerType: "800 Bi",
        time: "0849",
        info: "9 Car",
        departure: "09.33",
        by: "D2",
        headcode: "1D08",
        to: "HGT",
        next: "1A34"
    },
    {
        id: 19,
        arrival: "1Y11",
        powerType: "800 Bi",
        time: "0935",
        info: "9 Car",
        departure: "09.51",
        by: "D1",
        headcode: "5Y11",
        to: "FMP",
        next: "1W20"
    },
    {
        id: 20,
        arrival: "1Y08",
        powerType: "800 Bi",
        time: "0907",
        info: "9 Car",
        departure: "10.00",
        by: "D4",
        headcode: "1W11",
        to: "ABD",
        next: "1E30 LDS"
    },
    {
        id: 21,
        arrival: "1A06",
        powerType: "801 E",
        time: "0849",
        info: "9 Car",
        departure: "10.03",
        by: "D2",
        headcode: "1D09",
        to: "LDS",
        next: "1A30"
    },
    {
        id: 22,
        arrival: "5B82",
        powerType: "800 Bi",
        time: "0946",
        info: "5 Car",
        departure: "10.06",
        by: "D3",
        headcode: "1B82",
        to: "LCN",
        next: "1B85"
    },
    {
        id: 23,
        arrival: "1B81",
        powerType: "800 Bi",
        time: "0924",
        info: "9 Car",
        departure: "10.30",
        by: "D5",
        headcode: "3W96",
        to: "O+B KX",
        next: "1W96"
    },
    {
        id: 24,
        arrival: "1A13",
        powerType: "Mk4",
        time: "0959",
        departure: "10.30",
        by: "D6",
        headcode: "1S12",
        to: "EDB",
        next: "1E22"
    }
] 

export default HEADCODE_DATA;