const trainsLner = {
    "trains": [
        {
            "id": "1",
            "headcode": "1S01",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "5S01",
            "from": "XHT",
            "arriving": "0601",
            "stations": {
                "NewcastleA": "0622",
                "Morpeth": "0636",
                "Alnmouth": "0653",
                "Berwick-upon-Tweed": "0717",
                "Dunbar": "0741",
                "Edinburgh_Waveley": "0807"
            }
        },
        {
            "id": "2",
            "headcode": "1S02",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "3S02",
            "from": "XNL",
            "arriving": "0512",
            "stations": {
                "Doncaster": "0615",
                "YorkA": "0635",
                "York": "0639",
                "Darlington": "0708",
                "Durham": "0724",
                "NewcastleA": "0739",
                "Newcastle": "0743",
                "Alnmouth": "0808",
                "Berwick-upon-Tweed": "0830",
                "Dunbar": "0853",
                "Edinburgh_WaveleyA": "0922"
            }
        },
        {
            "id": "3",
            "headcode": "1S03",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "5S03",
            "from": "XNL",
            "arriving": "0651",
            "stations": {
                "Leeds": "0706",
                "YorkA": "0731",
                "York": "0736",
                "Durham": "0806",
                "NewcastleA": "0822",
                "Newcastle": "0837",
                "Morpeth": "0853",
                "Berwick-upon-Tweed": "0928",
                "Dunbar": "0953",
                "Edinburgh_WaveleyA": "1020",
                "Edinburgh_Waveley": "1028",
                "Haymarket": "1031",
                "Inverkeithing": "1047",
                "Kirkcaldy": "1104",
                "Leuchars": "1128",
                "Dundee": "1143",
                "Arbroath": "1200",
                "Montrose": "1216",
                "Stonehaven": "1239",
                "Aberdeen": "1305"
            }
        },
        {
            "id": "4",
            "headcode": "1D01",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "5D01",
            "from": "XBO",
            "arriving": "0501",
            "stations": {
                "London_Kings_Cross": "0555",
                "Stevenage": "0617",
                "Peterborough": "0647",
                "Grantham": "0706",
                "Newark_North_Gate": "0719",
                "Retford": "0734",
                "Doncaster": "0750",
                "Wakefield_Westgate": "0806",
                "Leeds": "0822"
            }
        },
        {
            "id": "5",
            "headcode": "1S04",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "3S04",
            "from": "KGX",
            "arriving": "0252",
            "stations": {
                "London_Kings_Cross": "0612",
                "Stevenage": "0634",
                "Peterborough": "0705",
                "Grantham": "0724",
                "Newark_North_Gate": "0737",
                "Retford": "0752",
                "Doncaster": "0812",
                "YorkA": "0832",
                "York": "0835",
                "Northallerton": "0853",
                "Darlington": "0908",
                "Durham": "0925",
                "NewcastleA": "0939",
                "Newcastle": "0947",
                "Edinburgh_Waveley": "1112"
            }
        },
        {
            "id": "6",
            "headcode": "1D02",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "5D02",
            "from": "XFD",
            "arriving": "0344",
            "stations": {
                "London_Kings_Cross": "0633",
                "Stevenage": "0655",
                "Peterborough": "0725",
                "Grantham": "0744",
                "Doncaster": "0818",
                "Wakefield_Westgate": "0834",
                "Leeds": "0851"
            }
        },
        {
            "id": "7",
            "headcode": "1S05",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "5S05",
            "from": "XBO",
            "arriving": "0615",
            "stations": {
                "London_Kings_Cross": "0700",
                "Peterborough": "0748",
                "YorkA": "0851",
                "York": "0855",
                "Darlington": "0924",
                "NewcastleA": "0951",
                "Newcastle": "0954",
                "Berwick-upon-Tweed": "1036",
                "Edinburgh_Waveley": "1122"
            }
        },
        {
            "id": "8",
            "headcode": "1D03",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "5D03",
            "from": "XFD",
            "arriving": "0255",
            "stations": {
                "London_Kings_Cross": "0703",
                "Peterborough": "0753",
                "Doncaster": "0843",
                "Wakefield_Westgate": "0900",
                "Leeds": "0917"
            }
        },
        {
            "id": "9",
            "headcode": "1N80",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "5N80",
            "from": "XBO",
            "arriving": "0609",
            "stations": {
                "London_Kings_Cross": "0706",
                "Stevenage": "0728",
                "Peterborough": "0800",
                "Grantham": "0819",
                "Newark_North_Gate": "0832",
                "Retford": "0847",
                "Doncaster": "0902",
                "York": "0925"
            }
        },
        {
            "id": "10",
            "headcode": "1S06",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "3S06",
            "from": "KGX",
            "arriving": "0031",
            "stations": {
                "London_Kings_Cross": "0730",
                "Peterborough": "0818",
                "Newark_North_Gate": "0846",
                "Doncaster": "0911",
                "YorkA": "0932",
                "York": "0935",
                "Darlington": "1005",
                "Durham": "1022",
                "NewcastleA": "1036",
                "Newcastle": "1042",
                "Alnmouth": "1107",
                "Edinburgh_Waveley": "1210"
            }
        },
        {
            "id": "11",
            "headcode": "1D04",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "5D04",
            "from": "XBO",
            "arriving": "0648",
            "stations": {
                "London_Kings_Cross": "0733",
                "Stevenage": "0755",
                "Grantham": "0841",
                "Doncaster": "0915",
                "Wakefield_Westgate": "0931",
                "Leeds": "0947"
            }
        },
        {
            "id": "12",
            "headcode": "1S07",
            "offPeak": true,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "1Y00",
            "from": "YRK",
            "arriving": "0659",
            "stations": {
                "London_Kings_Cross": "0800",
                "YorkA": "0952",
                "York": "0954",
                "Darlington": "1023",
                "NewcastleA": "1050",
                "Newcastle": "1053",
                "Berwick-upon-Tweed": "1135",
                "Edinburgh_Waveley": "1220"
            }
        },
        {
            "id": "13",
            "headcode": "1D05",
            "offPeak": true,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "1A01",
            "from": "LDS",
            "arriving": "0728",
            "stations": {
                "London_Kings_Cross": "0803",
                "Peterborough": "0857",
                "Doncaster": "0944",
                "Wakefield_Westgate": "1000",
                "Leeds": "1017"
            }
        },
        {
            "id": "14",
            "headcode": "1N08",
            "offPeak": true,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "5N08",
            "from": "XFD",
            "arriving": "0747",
            "stations": {
                "London_Kings_Cross": "0830",
                "Peterborough": "0918",
                "Newark_North_Gate": "0946",
                "Doncaster": "1010",
                "YorkA": "1032",
                "York": "1035",
                "Northallerton": "1053",
                "Darlington": "1109",
                "Durham": "1125",
                "Newcastle": "1141"
            }
        },
        {
            "id": "15",
            "headcode": "1D06",
            "offPeak": true,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "1A02",
            "from": "LDS",
            "arriving": "0747",
            "stations": {
                "London_Kings_Cross": "0833",
                "Stevenage": "0856",
                "Grantham": "0941",
                "Doncaster": "1015",
                "Wakefield_Westgate": "1031",
                "Leeds": "1047"
            }
        },
        {
            "id": "16",
            "headcode": "1S09",
            "offPeak": true,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "5S09",
            "from": "XBO",
            "arriving": "0825",
            "stations": {
                "London_Kings_Cross": "0900",
                "Peterborough": "0948",
                "YorkA": "1051",
                "York": "1054",
                "Darlington": "1123",
                "NewcastleA": "1150",
                "Newcastle": "1152",
                "Berwick-upon-Tweed": "1235",
                "Edinburgh_Waveley": "1319"
            }
        },
        {
            "id": "17",
            "headcode": "1D07",
            "offPeak": true,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "1Y03",
            "from": "NCL",
            "arriving": "0808",
            "stations": {
                "London_Kings_Cross": "0903",
                "Peterborough": "0952",
                "Doncaster": "1043",
                "Wakefield_Westgate": "1100",
                "Leeds": "1116"
            }
        },
        {
            "id": "18",
            "headcode": "1N81",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": false,
            "Planned previous working": "1A04",
            "from": "LDS",
            "arriving": "0829",
            "stations": {
                "London_Kings_Cross": "0906",
                "Stevenage": "0928",
                "Peterborough": "1001",
                "Grantham": "1021",
                "Newark_North_Gate": "1034",
                "Retford": "1049",
                "Doncaster": "1105",
                "York": "1130"
            }
        },
        {
            "id": "19",
            "headcode": "1S10",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": false,
            "Planned previous working": "1Y05",
            "from": "NCL",
            "arriving": "0838",
            "stations": {
                "London_Kings_Cross": "0930",
                "Peterborough": "1018",
                "Newark_North_Gate": "1046",
                "Doncaster": "1110",
                "YorkA": "1132",
                "York": "1135",
                "Darlington": "1205",
                "Durham": "1221",
                "NewcastleA": "1238",
                "Newcastle": "1241",
                "Morpeth": "1255",
                "Alnmouth": "1311",
                "Edinburgh_Waveley": "1415"
            }
        },
        {
            "id": "20",
            "headcode": "1D08",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": false,
            "Planned previous working": "1A06",
            "from": "LDS",
            "arriving": "0849",
            "stations": {
                "London_Kings_Cross": "0933",
                "Stevenage": "0956",
                "Grantham": "1041",
                "Doncaster": "1115",
                "Wakefield_Westgate": "1131",
                "Leeds": "1148"
            }
        },
        {
            "id": "21",
            "headcode": "1S11",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": false,
            "Planned previous working": "1B81",
            "from": "LCN",
            "arriving": "0924",
            "stations": {
                "London_Kings_Cross": "1000",
                "YorkA": "1151",
                "York": "1154",
                "Darlington": "1223",
                "NewcastleA": "1250",
                "Newcastle": "1255",
                "Berwick-upon-Tweed": "1338",
                "Edinburgh_WaveleyA": "1421",
                "Edinburgh_Waveley": "1428",
                "Haymarket": "1431",
                "Inverkeithing": "1447",
                "Kirkcaldy": "1504",
                "Leuchars": "1529",
                "Dundee": "1546",
                "Arbroath": "1604",
                "Montrose": "1620",
                "Stonehaven": "1643",
                "Aberdeen": "1706"
            }
        },
        {
            "id": "22",
            "headcode": "1D09",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1A09",
            "from": "LDS",
            "arriving": "0929",
            "stations": {
                "London_Kings_Cross": "1003",
                "Peterborough": "1051",
                "Doncaster": "1143",
                "Wakefield_Westgate": "1159",
                "Leeds": "1216"
            }
        },
        {
            "id": "23",
            "headcode": "1B82",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1A07",
            "from": "BDQ",
            "arriving": "0859",
            "stations": {
                "London_Kings_Cross": "1006",
                "Stevenage": "1028",
                "Peterborough": "1101",
                "Grantham": "1121",
                "Newark_North_Gate": "1135"
            }
        },
        {
            "id": "24",
            "headcode": "1S12",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1Y11",
            "from": "NCL",
            "arriving": "0935",
            "stations": {
                "London_Kings_Cross": "1030",
                "Peterborough": "1118",
                "Newark_North_Gate": "1146",
                "Doncaster": "1210",
                "YorkA": "1232",
                "York": "1235",
                "Northallerton": "1253",
                "Darlington": "1309",
                "Durham": "1325",
                "NewcastleA": "1339",
                "Newcastle": "1345",
                "Edinburgh_Waveley": "1516"
            }
        },
        {
            "id": "25",
            "headcode": "1D10",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1A13",
            "from": "SKI",
            "arriving": "0958",
            "stations": {
                "London_Kings_Cross": "1033",
                "Stevenage": "1056",
                "Grantham": "1141",
                "Doncaster": "1215",
                "Wakefield_Westgate": "1231",
                "Leeds": "1248"
            }
        },
        {
            "id": "26",
            "headcode": "1S13",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1E01",
            "from": "EDB",
            "arriving": "0940",
            "stations": {
                "London_Kings_Cross": "1100",
                "YorkA": "1251",
                "York": "1254",
                "Darlington": "1323",
                "NewcastleA": "1350",
                "Newcastle": "1352",
                "Berwick-upon-Tweed": "1435",
                "Edinburgh_Waveley": "1519"
            }
        },
        {
            "id": "27",
            "headcode": "1D11",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1A12",
            "from": "HUL",
            "arriving": "0951",
            "stations": {
                "London_Kings_Cross": "1103",
                "Peterborough": "1153",
                "Doncaster": "1243",
                "Wakefield_Westgate": "1300",
                "Leeds": "1316"
            }
        },
        {
            "id": "28",
            "headcode": "1N83",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1Y14",
            "from": "BWK",
            "arriving": "1001",
            "stations": {
                "London_Kings_Cross": "1106",
                "Stevenage": "1128",
                "Peterborough": "1159",
                "Grantham": "1219",
                "Newark_North_Gate": "1232",
                "Retford": "1247",
                "Doncaster": "1305",
                "York": "1330"
            }
        },
        {
            "id": "29",
            "headcode": "1S15",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1E02",
            "from": "EDB",
            "arriving": "1038",
            "stations": {
                "London_Kings_Cross": "1130",
                "Peterborough": "1218",
                "Newark_North_Gate": "1246",
                "Doncaster": "1310",
                "YorkA": "1332",
                "York": "1335",
                "Darlington": "1408",
                "Durham": "1424",
                "NewcastleA": "1439",
                "Newcastle": "1444",
                "Alnmouth": "1509",
                "Edinburgh_Waveley": "1614"
            }
        },
        {
            "id": "30",
            "headcode": "1D12",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1A18",
            "from": "LDS",
            "arriving": "1059",
            "stations": {
                "London_Kings_Cross": "1133",
                "Stevenage": "1156",
                "Grantham": "1241",
                "Doncaster": "1315",
                "Wakefield_Westgate": "1331",
                "Leeds": "1348"
            }
        },
        {
            "id": "31",
            "headcode": "1S16",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "3S16",
            "from": "XBO",
            "arriving": "1124",
            "stations": {
                "London_Kings_Cross": "1200",
                "YorkA": "1352",
                "York": "1354",
                "Darlington": "1423",
                "NewcastleA": "1451",
                "Newcastle": "1454",
                "Berwick-upon-Tweed": "1537",
                "Edinburgh_WaveleyA": "1620",
                "Edinburgh_Waveley": "1634",
                "Haymarket": "1637",
                "Falkirk_Grahamston": "1704",
                "Stirling": "1719",
                "Gleneagles": "1739",
                "Perth": "1758",
                "Pitlochry": "1830",
                "Kingussie": "1915",
                "Aviemore": "1928",
                "Inverness": "2006"
            }
        },
        {
            "id": "32",
            "headcode": "1D13",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1E03",
            "from": "STG",
            "arriving": "1047",
            "stations": {
                "London_Kings_Cross": "1203",
                "Peterborough": "1252",
                "Doncaster": "1343",
                "Wakefield_Westgate": "1359",
                "Leeds": "1416"
            }
        },
        {
            "id": "33",
            "headcode": "1B84",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1A15",
            "from": "HGT",
            "arriving": "1029",
            "stations": {
                "London_Kings_Cross": "1206",
                "Stevenage": "1228",
                "Peterborough": "1301",
                "Grantham": "1321",
                "Newark_North_Gate": "1336"
            }
        },
        {
            "id": "34",
            "headcode": "1N17",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1E04",
            "from": "EDB",
            "arriving": "1137",
            "stations": {
                "London_Kings_Cross": "1230",
                "Peterborough": "1318",
                "Newark_North_Gate": "1346",
                "Doncaster": "1411",
                "YorkA": "1432",
                "York": "1435",
                "Northallerton": "1453",
                "Darlington": "1509",
                "Durham": "1525",
                "Newcastle": "1541"
            }
        },
        {
            "id": "35",
            "headcode": "1D14",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1A19",
            "from": "LDS",
            "arriving": "1129",
            "stations": {
                "London_Kings_Cross": "1233",
                "Stevenage": "1256",
                "Grantham": "1341",
                "Doncaster": "1415",
                "Wakefield_Westgate": "1431",
                "Leeds": "1448"
            }
        },
        {
            "id": "36",
            "headcode": "1S18",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1Y82",
            "from": "YRK",
            "arriving": "1220",
            "stations": {
                "London_Kings_Cross": "1300",
                "Peterborough": "1348",
                "YorkA": "1451",
                "York": "1454",
                "Darlington": "1523",
                "NewcastleA": "1549",
                "Newcastle": "1552",
                "Berwick-upon-Tweed": "1634",
                "Edinburgh_WaveleyA": "1719"
            }
        },
        {
            "id": "37",
            "headcode": "1D15",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1A20",
            "from": "LDS",
            "arriving": "1159",
            "stations": {
                "London_Kings_Cross": "1303",
                "Peterborough": "1352",
                "Doncaster": "1443",
                "Wakefield_Westgate": "1459",
                "Leeds": "1516"
            }
        },
        {
            "id": "38",
            "headcode": "1N85",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1E05",
            "from": "EDB",
            "arriving": "1147",
            "stations": {
                "London_Kings_Cross": "1306",
                "Stevenage": "1328",
                "Peterborough": "1400",
                "Grantham": "1420",
                "Newark_North_Gate": "1433",
                "Retford": "1448",
                "Doncaster": "1504",
                "York": "1529"
            }
        },
        {
            "id": "39",
            "headcode": "1S19",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1A22",
            "from": "LDS",
            "arriving": "1228",
            "stations": {
                "London_Kings_Cross": "1330",
                "Peterborough": "1418",
                "Newark_North_Gate": "1446",
                "Doncaster": "1511",
                "YorkA": "1531",
                "York": "1535",
                "Northallerton": "1559",
                "Darlington": "1609",
                "Durham": "1625",
                "NewcastleA": "1639",
                "Newcastle": "1642",
                "Morpeth": "1655",
                "Alnmouth": "1710",
                "Edinburgh_WaveleyA": "1816"
            }
        },
        {
            "id": "40",
            "headcode": "1D16",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1E06",
            "from": "GLC",
            "arriving": "1238",
            "stations": {
                "London_Kings_Cross": "1333",
                "Peterborough": "1441",
                "Doncaster": "1515",
                "Wakefield_Westgate": "1531",
                "Leeds": "1548"
            }
        },
        {
            "id": "41",
            "headcode": "1S20",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1E07",
            "from": "EDB",
            "arriving": "1247",
            "stations": {
                "London_Kings_Cross": "1400",
                "YorkA": "1553",
                "York": "1555",
                "Darlington": "1624",
                "NewcastleA": "1651",
                "Newcastle": "1656",
                "Berwick-upon-Tweed": "1739",
                "Edinburgh_WaveleyA": "1822",
                "Edinburgh_Waveley": "1833",
                "Haymarket": "1836",
                "Inverkeithing": "1853",
                "Kirkcaldy": "1911",
                "Leuchars": "1939",
                "Dundee": "1953",
                "Arbroath": "2011",
                "Montrose": "2027",
                "Stonehaven": "2050",
                "Aberdeen": "2113"
            }
        },
        {
            "id": "42",
            "headcode": "1D17",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1A25",
            "from": "LDS",
            "arriving": "1259",
            "stations": {
                "London_Kings_Cross": "1403",
                "Peterborough": "1451",
                "Doncaster": "1543",
                "Wakefield_Westgate": "1559",
                "Leeds": "1616"
            }
        },
        {
            "id": "43",
            "headcode": "1B86",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1A26",
            "from": "LDS",
            "arriving": "1329",
            "stations": {
                "London_Kings_Cross": "1406",
                "Stevenage": "1428",
                "Peterborough": "1501",
                "Grantham": "1520",
                "Newark_North_Gate": "1534"
            }
        },
        {
            "id": "44",
            "headcode": "1N21",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1E08",
            "from": "EDB",
            "arriving": "1337",
            "stations": {
                "London_Kings_Cross": "1430",
                "Peterborough": "1519",
                "Newark_North_Gate": "1547",
                "Doncaster": "1611",
                "YorkA": "1632",
                "York": "1635",
                "Northallerton": "1653",
                "Darlington": "1709",
                "Durham": "1725",
                "Newcastle": "1741"
            }
        },
        {
            "id": "45",
            "headcode": "1D18",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1B83",
            "from": "NNG",
            "arriving": "1321",
            "stations": {
                "London_Kings_Cross": "1433",
                "Stevenage": "1456",
                "Grantham": "1542",
                "Doncaster": "1615",
                "Wakefield_Westgate": "1631",
                "Leeds": "1648"
            }
        },
        {
            "id": "46",
            "headcode": "1S22",
            "offPeak": true,
            "superOffPeak": false,
            "offPeakDay": true,
            "Planned previous working": "1Y84",
            "from": "YRK",
            "arriving": "1421",
            "stations": {
                "London_Kings_Cross": "1500",
                "YorkA": "1651",
                "York": "1654",
                "Darlington": "1723",
                "NewcastleA": "1750",
                "Newcastle": "1752",
                "Berwick-upon-Tweed": "1836",
                "Edinburgh_WaveleyA": "1918",
                "Edinburgh_Waveley": "1925",
                "Haymarket": "1928",
                "Falkirk_Grahamston": "1957",
                "Stirling": "2016"
            }
        },
        {
            "id": "47",
            "headcode": "1D19",
            "offPeak": true,
            "superOffPeak": false,
            "offPeakDay": true,
            "Planned previous working": "1A28",
            "from": "LDS",
            "arriving": "1359",
            "stations": {
                "London_Kings_Cross": "1503",
                "Peterborough": "1551",
                "Doncaster": "1643",
                "Wakefield_Westgate": "1659",
                "Leeds": "1716"
            }
        },
        {
            "id": "48",
            "headcode": "1N87",
            "offPeak": true,
            "superOffPeak": false,
            "offPeakDay": true,
            "Planned previous working": "1E09",
            "from": "EDB",
            "arriving": "1347",
            "stations": {
                "London_Kings_Cross": "1506",
                "Stevenage": "1528",
                "Peterborough": "1600",
                "Grantham": "1620",
                "Newark_North_Gate": "1633",
                "Retford": "1648",
                "Doncaster": "1704",
                "York": "1727"
            }
        },
        {
            "id": "49",
            "headcode": "1S23",
            "offPeak": true,
            "superOffPeak": false,
            "offPeakDay": true,
            "Planned previous working": "1A29",
            "from": "LDS",
            "arriving": "1429",
            "stations": {
                "London_Kings_Cross": "1530",
                "Peterborough": "1618",
                "Newark_North_Gate": "1646",
                "Doncaster": "1710",
                "YorkA": "1731",
                "York": "1735",
                "Northallerton": "1754",
                "Darlington": "1810",
                "Durham": "1826",
                "NewcastleA": "1840",
                "Newcastle": "1844",
                "Alnmouth": "1909",
                "Edinburgh_WaveleyA": "2013",
                "Edinburgh_Waveley": "2017",
                "Haymarket": "2021",
                "Motherwell": "2103",
                "Glasgow_Central": "2127"
            }
        },
        {
            "id": "50",
            "headcode": "1D20",
            "offPeak": true,
            "superOffPeak": false,
            "offPeakDay": true,
            "Planned previous working": "1E10",
            "from": "EDB",
            "arriving": "1437",
            "stations": {
                "London_Kings_Cross": "1533",
                "Stevenage": "1556",
                "Grantham": "1641",
                "Doncaster": "1717",
                "Wakefield_Westgate": "1733",
                "Leeds": "1750"
            }
        },
        {
            "id": "51",
            "headcode": "1S24",
            "offPeak": true,
            "superOffPeak": false,
            "offPeakDay": true,
            "Planned previous working": "1A30",
            "from": "LDS",
            "arriving": "1459",
            "stations": {
                "London_Kings_Cross": "1600",
                "YorkA": "1752",
                "York": "1756",
                "Darlington": "1825",
                "NewcastleA": "1851",
                "Newcastle": "1854",
                "Berwick-upon-Tweed": "1937",
                "Edinburgh_WaveleyA": "2020",
                "Edinburgh_Waveley": "2032",
                "Haymarket": "2035",
                "Inverkeithing": "2051",
                "Kirkcaldy": "2109",
                "Leuchars": "2137",
                "Dundee": "2152",
                "Arbroath": "2209",
                "Montrose": "2225",
                "Stonehaven": "2248",
                "Aberdeen": "2312"
            }
        },
        {
            "id": "52",
            "headcode": "1D21",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "1E11",
            "from": "ABD",
            "arriving": "1449",
            "stations": {
                "London_Kings_Cross": "1603",
                "Peterborough": "1652",
                "Doncaster": "1741",
                "Wakefield_Westgate": "1759",
                "Leeds": "1816"
            }
        },
        {
            "id": "53",
            "headcode": "1B88",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "1B85",
            "from": "NNG",
            "arriving": "1521",
            "stations": {
                "London_Kings_Cross": "1606",
                "Stevenage": "1628",
                "Peterborough": "1702",
                "Grantham": "1722",
                "Newark_North_Gate": "1736"
            }
        },
        {
            "id": "54",
            "headcode": "1S25",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "1Y32",
            "from": "NCL",
            "arriving": "1537",
            "stations": {
                "London_Kings_Cross": "1630",
                "Peterborough": "1718",
                "Newark_North_Gate": "1746",
                "Doncaster": "1816",
                "YorkA": "1836",
                "York": "1839",
                "Northallerton": "1857",
                "Darlington": "1912",
                "Durham": "1929",
                "NewcastleA": "1943",
                "Newcastle": "1945",
                "Morpeth": "1959",
                "Edinburgh_Waveley": "2114"
            }
        },
        {
            "id": "55",
            "headcode": "1D22",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "1A31",
            "from": "LDS",
            "arriving": "1529",
            "stations": {
                "London_Kings_Cross": "1633",
                "Stevenage": "1655",
                "Grantham": "1741",
                "Retford": "1804",
                "Doncaster": "1819",
                "Wakefield_Westgate": "1835",
                "Leeds": "1852"
            }
        },
        {
            "id": "56",
            "headcode": "1S26",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "1E13",
            "from": "INV",
            "arriving": "1547",
            "stations": {
                "London_Kings_Cross": "1700",
                "YorkA": "1850",
                "York": "1853",
                "Darlington": "1922",
                "NewcastleA": "1949",
                "Newcastle": "1953",
                "Berwick-upon-Tweed": "2036",
                "Edinburgh_WaveleyA": "2121"
            }
        },
        {
            "id": "57",
            "headcode": "1D23",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "1A34",
            "from": "LDS",
            "arriving": "1631",
            "stations": {
                "London_Kings_Cross": "1703",
                "Peterborough": "1751",
                "Doncaster": "1843",
                "Wakefield_Westgate": "1900",
                "Leeds": "1917"
            }
        },
        {
            "id": "58",
            "headcode": "1H10",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "1A33",
            "from": "LDS",
            "arriving": "1559",
            "stations": {
                "London_Kings_Cross": "1718",
                "Peterborough": "1809",
                "Grantham": "1829",
                "Newark_North_Gate": "1842",
                "Doncaster": "1911",
                "Selby": "1926",
                "Brough": "1948",
                "Hull": "2005"
            }
        },
        {
            "id": "59",
            "headcode": "1S27",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "1Y86",
            "from": "YRK",
            "arriving": "1621",
            "stations": {
                "London_Kings_Cross": "1730",
                "Peterborough": "1819",
                "Newark_North_Gate": "1847",
                "YorkA": "1927",
                "York": "1930",
                "Darlington": "1959",
                "Durham": "2015",
                "NewcastleA": "2029",
                "Newcastle": "2033",
                "Alnmouth": "2100",
                "Dunbar": "2142",
                "Edinburgh_WaveleyA": "2210"
            }
        },
        {
            "id": "60",
            "headcode": "1D24",
            "offPeak": false,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "1A36",
            "from": "LDS",
            "arriving": "1659",
            "stations": {
                "London_Kings_Cross": "1733",
                "Stevenage": "1755",
                "Grantham": "1842",
                "Doncaster": "1916",
                "Wakefield_Westgate": "1932",
                "LeedsA": "1947",
                "Leeds": "1959",
                "Harrogate": "2025"
            }
        },
        {
            "id": "61",
            "headcode": "1D25",
            "offPeak": true,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "1E14",
            "from": "EDB",
            "arriving": "1637",
            "stations": {
                "London_Kings_Cross": "1748",
                "Peterborough": "1838",
                "Grantham": "1906",
                "Retford": "1929",
                "Doncaster": "1945",
                "Wakefield_Westgate": "2001",
                "Leeds": "2017"
            }
        },
        {
            "id": "62",
            "headcode": "1S28",
            "offPeak": true,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "1E15",
            "from": "ABD",
            "arriving": "1648",
            "stations": {
                "London_Kings_Cross": "1800",
                "YorkA": "1949",
                "York": "1952",
                "Darlington": "2022",
                "NewcastleA": "2048",
                "Newcastle": "2051",
                "Berwick-upon-Tweed": "2134",
                "Edinburgh_WaveleyA": "2219"
            }
        },
        {
            "id": "63",
            "headcode": "1D26",
            "offPeak": true,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "1B87",
            "from": "NNG",
            "arriving": "1721",
            "stations": {
                "London_Kings_Cross": "1803",
                "Peterborough": "1853",
                "Newark_North_Gate": "1923",
                "Doncaster": "1950",
                "Wakefield_Westgate": "2006",
                "LeedsA": "2021",
                "Leeds": "2039",
                "Keighley": "2101",
                "Skipton": "2119"
            }
        },
        {
            "id": "64",
            "headcode": "1N29",
            "offPeak": true,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "1A37",
            "from": "LDS",
            "arriving": "1729",
            "stations": {
                "London_Kings_Cross": "1818",
                "Peterborough": "1906",
                "Grantham": "1927",
                "YorkA": "2015",
                "York": "2018",
                "Northallerton": "2036",
                "Darlington": "2051",
                "Durham": "2108",
                "NewcastleA": "2124"
            }
        },
        {
            "id": "65",
            "headcode": "1S30",
            "offPeak": true,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "1E16",
            "from": "EDB",
            "arriving": "1738",
            "stations": {
                "London_Kings_Cross": "1830",
                "Peterborough": "1918",
                "Newark_North_Gate": "1946",
                "Doncaster": "2016",
                "YorkA": "2036",
                "York": "2039",
                "Darlington": "2108",
                "Durham": "2124",
                "NewcastleA": "2138",
                "Newcastle": "2141",
                "Morpeth": "2154",
                "Alnmouth": "2210",
                "Edinburgh_WaveleyA": "2318"
            }
        },
        {
            "id": "66",
            "headcode": "1D28",
            "offPeak": true,
            "superOffPeak": false,
            "offPeakDay": false,
            "Planned previous working": "1E17",
            "from": "EDB",
            "arriving": "1750",
            "stations": {
                "London_Kings_Cross": "1833",
                "Stevenage": "1855",
                "Grantham": "1941",
                "Retford": "2004",
                "Doncaster": "2022",
                "Wakefield_Westgate": "2038",
                "LeedsA": "2054",
                "Leeds": "2106",
                "Shipley": "2118",
                "Bradford_Forster_Square": "2129"
            }
        },
        {
            "id": "67",
            "headcode": "1S31",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": false,
            "Planned previous working": "1A39",
            "from": "LDS",
            "arriving": "1759",
            "stations": {
                "London_Kings_Cross": "1900",
                "YorkA": "2054",
                "York": "2057",
                "Darlington": "2126",
                "NewcastleA": "2152",
                "Newcastle": "2155",
                "Berwick-upon-Tweed": "2238",
                "Edinburgh_WaveleyA": "2331"
            }
        },
        {
            "id": "68",
            "headcode": "1D29",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1A40",
            "from": "LDS",
            "arriving": "1829",
            "stations": {
                "London_Kings_Cross": "1903",
                "Peterborough": "1952",
                "Doncaster": "2042",
                "Wakefield_Westgate": "2059",
                "Leeds": "2116"
            }
        },
        {
            "id": "69",
            "headcode": "1B90",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1Y88",
            "from": "YRK",
            "arriving": "1825",
            "stations": {
                "London_Kings_Cross": "1906",
                "Stevenage": "1928",
                "Peterborough": "2000",
                "Grantham": "2020",
                "Newark_North_Gate": "2035",
                "Lincon_Central": "2101"
            }
        },
        {
            "id": "70",
            "headcode": "1N32",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1E19",
            "from": "EDB",
            "arriving": "1847",
            "stations": {
                "London_Kings_Cross": "1930",
                "Peterborough": "2018",
                "Newark_North_Gate": "2046",
                "Doncaster": "2110",
                "YorkA": "2131",
                "York": "2133",
                "Northallerton": "2152",
                "Darlington": "2207",
                "Durham": "2223",
                "NewcastleA": "2239"
            }
        },
        {
            "id": "71",
            "headcode": "1D30",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1A41",
            "from": "LDS",
            "arriving": "1859",
            "stations": {
                "London_Kings_Cross": "1933",
                "Stevenage": "1955",
                "Grantham": "2041",
                "Doncaster": "2114",
                "Wakefield_Westgate": "2130",
                "Leeds": "2147"
            }
        },
        {
            "id": "72",
            "headcode": "1N33",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1B89",
            "from": "NNG",
            "arriving": "1921",
            "stations": {
                "London_Kings_Cross": "2000",
                "YorkA": "2148",
                "York": "2153",
                "Darlington": "2223",
                "Durham": "2239",
                "NewcastleA": "2254",
                "Newcastle": "2300",
                "Sunderland": "2323"
            }
        },
        {
            "id": "73",
            "headcode": "1D31",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1A43",
            "from": "LDS",
            "arriving": "1930",
            "stations": {
                "London_Kings_Cross": "2003",
                "Peterborough": "2052",
                "Newark_North_Gate": "2120",
                "Doncaster": "2145",
                "Wakefield_Westgate": "2205",
                "Leeds": "2221"
            }
        },
        {
            "id": "74",
            "headcode": "1D32",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1A45",
            "from": "LDS",
            "arriving": "1959",
            "stations": {
                "London_Kings_Cross": "2033",
                "Stevenage": "2055",
                "Peterborough": "2126",
                "Grantham": "2145",
                "Newark_North_Gate": "2158",
                "Doncaster": "2223",
                "Wakefield_Westgate": "2239",
                "Leeds": "2257"
            }
        },
        {
            "id": "75",
            "headcode": "1N34",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1A46",
            "from": "LDS",
            "arriving": "2029",
            "stations": {
                "London_Kings_Cross": "2100",
                "Stevenage": "2122",
                "Peterborough": "2153",
                "Newark_North_Gate": "2221",
                "Doncaster": "2247",
                "YorkA": "2308",
                "York": "2312",
                "Northallerton": "2342",
                "Darlington": "2357",
                "Durham": "0013",
                "NewcastleA": "0043"
            }
        },
        {
            "id": "76",
            "headcode": "1D33",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1Y90",
            "from": "YRK",
            "arriving": "2021",
            "stations": {
                "London_Kings_Cross": "2133",
                "Stevenage": "2156",
                "Peterborough": "2228",
                "Grantham": "2249",
                "Newark_North_Gate": "2302",
                "Retford": "2317",
                "Doncaster": "2337",
                "Wakefield_Westgate": "2354",
                "Leeds": "0010"
            }
        },
        {
            "id": "77",
            "headcode": "1N35",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1A48",
            "from": "LDS",
            "arriving": "2059",
            "stations": {
                "London_Kings_Cross": "2200",
                "Peterborough": "2249",
                "Grantham": "2309",
                "Newark_North_Gate": "2323",
                "Doncaster": "2352",
                "YorkA": "0038",
                "York": "0041",
                "Northallerton": "0109",
                "Darlington": "0123",
                "Durham": "0142",
                "NewcastleA": "0215"
            }
        },
        {
            "id": "78",
            "headcode": "1N36",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "3N36",
            "from": "KGX",
            "arriving": "2236",
            "stations": {
                "London_Kings_Cross": "2300",
                "Peterborough": "2344",
                "Grantham": "0013",
                "Newark_North_Gate": "0025",
                "Doncaster": "0058",
                "York": "0134"
            }
        },
        {
            "id": "79",
            "headcode": "1D36",
            "offPeak": true,
            "superOffPeak": true,
            "offPeakDay": true,
            "Planned previous working": "1E25",
            "from": "ABD",
            "arriving": "2208",
            "stations": {
                "London_Kings_Cross": "2333",
                "Peterborough": "0016",
                "Grantham": "0045",
                "Newark_North_Gate": "0057",
                "Doncaster": "0124",
                "Leeds": "0236"
            }
        }
    ]
}

export default trainsLner;
